# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
      - master
      - develop
      - feature/*
  paths:
    include:
      - proj2/**

pr:
  branches:
    include:
      - master
      - main
      - develop
  paths:
    include:
      - proj2/**

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    Python311:
      python.version: '3.11'

variables:
  proj2Key: 'manishahaulbert-csbytes_proj2'

steps:
- checkout: self
  fetchDepth: 0
  lfs: true
  displayName: 'Checkout Source Code'

- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

# 1. Detect Changes
- script: |
    # Check for changes in specific directories
    CHANGED_FILES=$(git diff --name-only HEAD~1)
    echo "Files changed: $CHANGED_FILES"    
   
    if echo "$CHANGED_FILES" | grep -q "proj2"; then
      echo "##vso[task.setvariable variable=runProj2;isOutput=true]true"
      echo "Detected changes in Proj2"
    fi

  name: DetermineChanges
  displayName: 'Detect Changed projects'

# 2. Install Dependencies (Global)
- script: |
    python -m pip install --upgrade pip
    pip install pytest pytest-cov
  displayName: 'Install Base Tools'

# --- Proj2 Block ---
- script: |
    pip install -e ./proj2
    export PYTHONPATH="$(System.DefaultWorkingDirectory)"
    pytest proj2/tests \
      --junitxml=proj2-results.xml \
      --cov=. \
      --cov-report=xml:proj2-coverage.xml
  displayName: 'Run proj2 Tests'
  condition: eq(variables['DetermineChanges.runProj2'], 'true')

- task: SonarQubePrepare@8
  condition: and(eq(variables['python.version'], '3.11'), eq(variables['DetermineChanges.runProj2'], 'true'))
  inputs:
    SonarQube: 'monorepo20261'
    scannerMode: 'CLI'
    configMode: 'manual'
    cliProjectKey: '$(proj2Key)'
    extraProperties: |
      sonar.qualitygate.wait=true
      sonar.qualitygate.timeout=600
      sonar.projectBaseDir=proj2
      sonar.sources=helloworld2.py
      sonar.exclusions=tests/**
      sonar.tests=tests
      sonar.python.xunit.reportPath=$(System.DefaultWorkingDirectory)/proj2-results.xml
      sonar.python.coverage.reportPaths=$(System.DefaultWorkingDirectory)/proj2-coverage.xml

# 3. Analyze & Publish (Combined)
- task: SonarQubeAnalyze@8
  continueOnError: false
  condition: eq(variables['python.version'], '3.11')
  displayName: 'Run Sonar Analysis'
  inputs:
    jdkversion: 'JAVA_HOME_17_X64'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFiles: '*-results.xml'